### ISSUE TITLE
Problema de permisos PayU

### ISSUE THREAD

**Issue by yunierescobar** [saulmoralespa/woo-payu-latam-sdk#1]
Hola! Ante todo mi agradecimiento por el complemento. 
Lo he estado probando y tengo dos problemas:
1. Utilizándolo en ambiente de producción, tengo este error: payU Latam SDK: verifique que haya ingresado correctamente el ID del comercio, el ID de la cuenta, Api Key y Apilogin. Para realizar pruebas use las credenciales proporcionadas por payU Click aquí para ver Mensaje de error: No cuenta con los permisos requeridos para efectuar la operación solicitada, para mayor información comuníquese con el servicio de atención al cliente. error de código: 0

Todos los datos de ID del comercio, el ID de la cuenta, Api Key y Apilogin están correctos.

2. En México (que es el pais donde estoy probando el complemento) no existe el DNI, sin embargo el complemento agrega un campo de texto obligatorio para poner ese número. Sería bueno eliminarlo de los países donde no sea necesario dicho DNI en el proceso de pago.

Saludos!

**Comment by yunierescobar** [comment]
Para el problema número 1 he hablado con atención a clientes de PayU y tienen que autorizar el uso de los servicios API. Así que en este caso no es problema del plugin sino de dichos permisos de PayU.

El problema  número dos sigue vigente.

Saludos

**Comment by saulmoralespa** [comment]
Requiere la activación del SDk por parte del soporte de payU para el procesamiento de pagos
